"""
Children's Story Time Generator - Main Application

A multi-agent AI system that generates engaging, age-appropriate children's stories
using LangChain and LangGraph with GitHub Models API.

Agents:
- Story Planner: Creates story outlines
- Story Writer: Writes narrative based on outline
- Story Validator: Reviews and approves/requests revision
"""

import os
import json
from datetime import datetime
from typing import TypedDict, Annotated
from pathlib import Path
from dotenv import load_dotenv

# LangGraph and LangChain imports
try:
    from langgraph.graph import StateGraph, START, END
    from langgraph.graph.message import add_messages
    from langgraph.types import Command
    from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
except ImportError as e:
    print(f"Error: Required packages not installed. Please run: pip install -r requirements.txt")
    print(f"Import error: {e}")
    exit(1)

# Load environment variables
load_dotenv()

# Configuration
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
API_ENDPOINT = os.getenv("API_ENDPOINT", "https://models.github.ai/inference")
MODEL_NAME = os.getenv("MODEL_NAME", "openai/gpt-4o-mini")
OUTPUT_DIR = Path(__file__).parent / "output"

# Validate GitHub Token
if not GITHUB_TOKEN or GITHUB_TOKEN == "your_github_token_here":
    print("⚠️  Warning: GITHUB_TOKEN not configured in .env file")
    print("Please set your GitHub token to enable API calls")


# ============================================================================
# State Management
# ============================================================================

class State(TypedDict):
    """State container for story generation workflow"""
    messages: Annotated[list, add_messages]
    story_outline: str
    story_narrative: str
    validation_status: str
    revision_count: int


# ============================================================================
# Placeholder Agent Functions
# ============================================================================

def planner_node(state: State) -> State:
    """
    Story Planner Agent - Creates story outline from user input
    
    Expected to generate:
    - Story title
    - Target age group
    - Main characters
    - Plot outline
    - Learning lesson/moral
    - Tone recommendations
    """
    print("\n📋 [PLANNER] Processing story outline request...")
    
    # Get the last user message
    if state["messages"]:
        last_message = state["messages"][-1].content
        print(f"   Input: {last_message}")
    
    # Placeholder: In Phase 2, this will call the actual planner agent
    outline = """
    [PLACEHOLDER - Story Outline]
    Title: To be generated by planner agent
    Age Group: To be determined
    Characters: To be created
    Plot: To be developed
    Lesson: To be defined
    """
    
    state["story_outline"] = outline
    ai_message = AIMessage(content=f"Story outline created:\n{outline}")
    state["messages"] = state["messages"] + [ai_message]
    
    print("   ✓ Outline created, passing to writer...")
    return state


def writer_node(state: State) -> State:
    """
    Story Writer Agent - Generates narrative based on outline
    
    Expected to generate:
    - Age-appropriate language
    - Engaging dialogue
    - Sensory descriptions
    - Complete story arc
    """
    print("\n✍️  [WRITER] Generating story narrative...")
    
    if not state["story_outline"]:
        print("   ⚠️  No outline available")
        return state
    
    print(f"   Using outline: {state['story_outline'][:50]}...")
    
    # Placeholder: In Phase 2, this will call the actual writer agent
    narrative = """
    [PLACEHOLDER - Story Narrative]
    Once upon a time...
    
    [Full story to be generated by writer agent]
    
    The End.
    """
    
    state["story_narrative"] = narrative
    ai_message = AIMessage(content=f"Story written:\n{narrative}")
    state["messages"] = state["messages"] + [ai_message]
    
    print("   ✓ Story generated, passing to validator...")
    return state


def validator_node(state: State) -> Command | State:
    """
    Story Validator Agent - Reviews story for quality and age-appropriateness
    
    Returns:
    - APPROVED: Story is ready
    - REVISION NEEDED: Route back to writer with feedback
    """
    print("\n✅ [VALIDATOR] Reviewing story...")
    
    if not state["story_narrative"]:
        print("   ⚠️  No story to validate")
        return state
    
    print(f"   Reviewing story: {state['story_narrative'][:50]}...")
    
    # Placeholder: In Phase 2, this will call the actual validator agent
    # For now, always approve to test the workflow
    state["validation_status"] = "APPROVED"
    ai_message = AIMessage(content="Story validation: APPROVED ✓")
    state["messages"] = state["messages"] + [ai_message]
    
    print("   ✓ Story APPROVED")
    print("   → Routing to END")
    
    return state


# ============================================================================
# Workflow Setup
# ============================================================================

def build_workflow():
    """Construct the StateGraph for story generation workflow"""
    
    print("\n🔨 Building workflow graph...")
    
    # Create the workflow graph
    workflow = StateGraph(State)
    
    # Add nodes
    workflow.add_node("planner", planner_node)
    workflow.add_node("writer", writer_node)
    workflow.add_node("validator", validator_node)
    
    # Set entry point
    workflow.add_edge(START, "planner")
    
    # Define workflow edges
    workflow.add_edge("planner", "writer")
    workflow.add_edge("writer", "validator")
    workflow.add_edge("validator", END)
    
    print("   ✓ Workflow graph created")
    print("   ✓ Nodes: [planner → writer → validator → END]")
    
    # Compile the graph
    graph = workflow.compile()
    return graph


# ============================================================================
# Output Management
# ============================================================================

def save_story(title: str, story: str, metadata: dict) -> Path:
    """Save generated story to markdown file"""
    
    OUTPUT_DIR.mkdir(exist_ok=True)
    
    # Create filename from title
    filename = f"story_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    filepath = OUTPUT_DIR / filename
    
    # Format story with metadata
    content = f"""# {title}

## Metadata
- **Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Age Group**: {metadata.get('age_group', 'Not specified')}
- **Theme**: {metadata.get('theme', 'Not specified')}
- **Lesson**: {metadata.get('lesson', 'Not specified')}

## Story

{story}
"""
    
    filepath.write_text(content)
    print(f"\n💾 Story saved to: {filepath}")
    return filepath


# ============================================================================
# Main Application
# ============================================================================

def collect_user_input() -> dict:
    """Collect story requirements from user"""
    
    print("\n" + "=" * 60)
    print("🎨 Children's Story Time Generator")
    print("=" * 60)
    
    print("\nLet's create a story! Please provide the following information:\n")
    
    theme = input("📚 Story Theme/Topic: ").strip()
    if not theme:
        theme = "A magical adventure"
    
    print("\nAge Group:")
    print("  1) 3-5 years (Preschool)")
    print("  2) 6-8 years (Early Elementary)")
    print("  3) 9-12 years (Middle Elementary)")
    
    age_choice = input("Select age group (1-3) [default: 1]: ").strip() or "1"
    age_map = {
        "1": "3-5 years",
        "2": "6-8 years",
        "3": "9-12 years"
    }
    age_group = age_map.get(age_choice, "3-5 years")
    
    lesson = input("\n💡 Learning Lesson/Moral (optional, press Enter to skip): ").strip()
    
    length = input("\n📏 Story Length (short/medium/long) [default: medium]: ").strip().lower() or "medium"
    
    return {
        "theme": theme,
        "age_group": age_group,
        "lesson": lesson or "Not specified",
        "length": length,
        "user_input": f"Theme: {theme}, Age: {age_group}"
    }


def main():
    """Main application entry point"""
    
    print("\n🚀 Initializing Story Time Generator...")
    
    # Check configuration
    if not GITHUB_TOKEN or GITHUB_TOKEN == "your_github_token_here":
        print("\n⚠️  GITHUB_TOKEN is not configured properly")
        print("Setup instructions:")
        print("1. Copy .env.example to .env")
        print("2. Add your GitHub token from https://github.com/settings/tokens")
        print("\nContinuing with placeholder responses...\n")
    
    # Collect user input
    user_data = collect_user_input()
    
    # Initialize state
    initial_state = {
        "messages": [HumanMessage(content=user_data["user_input"])],
        "story_outline": "",
        "story_narrative": "",
        "validation_status": "",
        "revision_count": 0,
    }
    
    # Build and run workflow
    print("\n" + "=" * 60)
    print("🎬 Starting Story Generation Workflow")
    print("=" * 60)
    
    workflow = build_workflow()
    
    print("\n🔄 Running workflow...\n")
    final_state = workflow.invoke(initial_state)
    
    # Display results
    print("\n" + "=" * 60)
    print("📖 Story Generation Complete!")
    print("=" * 60)
    
    print(f"\n✓ Outline:\n{final_state['story_outline']}")
    print(f"\n✓ Narrative:\n{final_state['story_narrative']}")
    print(f"\n✓ Status: {final_state['validation_status']}")
    
    # Save story
    metadata = {
        "age_group": user_data["age_group"],
        "theme": user_data["theme"],
        "lesson": user_data["lesson"]
    }
    save_story(
        title=user_data["theme"],
        story=final_state["story_narrative"],
        metadata=metadata
    )
    
    print("\n✅ Story generation workflow completed!")


if __name__ == "__main__":
    main()
